#!/bin/sh

sinks=$(pactl list sinks | grep Name | sed "s/\tName: //" )

# if [ -n $(echo $sinks | grep -o alsa_output.usb-Lenovo_ThinkPad_USB-C_Dock_Gen3_USB_Audio_000000000000-00.analog-stereo) ];
# then
# 	sinks=$(echo $sinks | sed "s/alsa_output.pci-0000_00_1f.3.analog-stereo //")
# fi

total=$(echo $sinks | tr -s '[:blank:]' '\n' | wc -l)
current=$(pactl get-default-sink)
next=$(($(($(echo $sinks | tr -s '[:blank:]' '\n' | cat -n | grep $current | cut -f 1))) % $(($total))))
new=$(echo $sinks | tr -s '[:blank:]' '\n' | head -n$(($next + 1)) | tail -n1)
pactl set-default-sink $new
